kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 37017 # database
      hostPort: 37017
      protocol: TCP
    - containerPort: 33000 # frontend
      hostPort: 33000
      protocol: TCP
    - containerPort: 30080 # nginx
      hostPort: 30080
      protocol: TCP
    - containerPort: 35000 # photo retrieval
      hostPort: 35000
      protocol: TCP
    - containerPort: 34000 # upload
      hostPort: 34000
      protocol: TCP
  - role: worker
  - role: worker